AFP_URL="http://afp.sourceforge.net/browser_info/current/AFP"
HOL_URL="https://isabelle.in.tum.de/dist/library/HOL"
  
if test $# -eq 0; then
  echo "Usage: $0 directories"
  echo "Fix URLs in html-files generated by Isabelle/HOL such that AFP and HOL links point to the AFP and Isabelle/HOL homepages"
  exit 1
fi
  
  
# Fixup URLs in browser_info

for i in `find $@ -name '*.html'`; do
  sed -i -re "s|../../AFP/|$AFP_URL/|g; s|../../HOL/|$HOL_URL/|g" $i
  
done
